### ISSUE TITLE
TypingError using annotate_seqlets/tomtom

### ISSUE THREAD

**Issue by shirondru** [jmschrei/tangermeme#22] opened 2024-10-13 23:33 UTC
Thanks for this awesome resource! I've run into an issue with tomtom, and have reproduced it using the repo's test data.

```python
from tangermeme.annotate import annotate_seqlets
from tangermeme.seqlet import recursive_seqlets
import torch

X = torch.load("X_gata.torch")
X_attr = torch.load("X_gata_attr.torch")
X_contrib = (X * X_attr).sum(axis=1)

seqlets = recursive_seqlets(X_contrib)
assert seqlets.shape == (20, 5)
idxs, pvals = annotate_seqlets(X, seqlets, "test.meme")
``` 

An error is raised here:
```python
--> 497 results = _tomtom(Q, T, Q_lens, T_lens, Q_norm, T_norm, rr_inv, rr_counts, 
    498 	n_nearest, n_score_bins, n_median_bins, n_cache, 
    499 	int(reverse_complement))
``` 
And here are the details:
```python
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function iadd>) found for signature:
 
 >>> iadd(Literal[int](0), array(int32, 1d, C))
 
There are 18 candidate implementations:
     - Of which 16 did not match due to:
     Overload of function 'iadd': File: <numerous>: Line N/A.
       With argument(s): '(int64, array(int32, 1d, C))':
      No match.
     - Of which 2 did not match due to:
     Operator Overload in function 'iadd': File: unknown: Line unknown.
       With argument(s): '(int64, array(int32, 1d, C))':
      No match for registered cases:
       * (int64, int64) -> int64
       * (int64, uint64) -> int64
       * (uint64, int64) -> int64
       * (uint64, uint64) -> uint64
       * (float32, float32) -> float32
       * (float64, float64) -> float64
       * (complex64, complex64) -> complex64
       * (complex128, complex128) -> complex128

During: typing of intrinsic-call at /pollard/home/sdrusinsky/miniforge3/envs/OligoGene/lib/python3.12/site-packages/tangermeme/tools/tomtom.py (242)

File "../../../../../../../../../home/sdrusinsky/miniforge3/envs/OligoGene/lib/python3.12/site-packages/tangermeme/tools/tomtom.py", line 242:
def _p_values(gamma, B_cdfs, rr_inv, T_lens, nq, offset, n_bins, results):
    <source elided>
					j, t_idx = uint64(j), uint64(total_offset + j + k)
					score += gamma[j, rr_inv[t_idx]]
     ^

During: resolving callee type: type(CPUDispatcher(<function _p_values at 0x7f0673edeac0>))
During: typing of call at /pollard/home/sdrusinsky/miniforge3/envs/OligoGene/lib/python3.12/site-packages/tangermeme/tools/tomtom.py (341)

During: resolving callee type: type(CPUDispatcher(<function _p_values at 0x7f0673edeac0>))
During: typing of call at /pollard/home/sdrusinsky/miniforge3/envs/OligoGene/lib/python3.12/site-packages/tangermeme/tools/tomtom.py (341)


File "../../../../../../../../../home/sdrusinsky/miniforge3/envs/OligoGene/lib/python3.12/site-packages/tangermeme/tools/tomtom.py", line 341:
def _tomtom(Q, T, Q_lens, T_lens, Q_norm, T_norm, rr_inv, rr_counts, n_nearest, 
    <source elided>

		_p_values(_gamma[pid], _B[pid], rr_inv, T_lens, nq, offset, 
  ^


``` 

The problematic line seems to be `score += gamma[j, rr_inv[t_idx]]`. I believe the error is caused because numba does not like adding an int32 (or some other dtype) to a literal int. `score` is defined as 0 within `_p_values` whereas values in the `gamma` array have a different type (i believe they are int32). If that's right, then I would think this could be fixed by making the dtype of `score` compatible with those in `gamma`.

I tried updating `score` in line 233 of `tomtom.py` like so: 
```python
score = np.int32(0)
``` 
But this did not fix the problem, even though traceback suggests `score` is now int32 and `gamma` contains int32 values.

**Comment by shirondru** [comment] 2024-10-13 23:37
I forgot to mention, this is using:
 tangermeme 0.4.0
numba 0.60.0
numpy 2.0.0
pytorch 2.3.1

**Comment by jmschrei** [comment] 2024-10-14 08:00
Thanks for the report, and for trying to fix it. GitHub actions is also having this issue but I can't reproduce it on several machines that I've tried and haven't been able to easily fix it on my end (waiting for GitHub actions to install/run is a huge pain). The error doesn't make sense to me because numba is good at autocasting or recasting things to work properly. I also tried what you mentioned and it didn't help.

What OS and Python version are you using? How did you install the repo?

**Comment by Vejni** [comment] 2024-10-14 09:59
Hi there, I have also run into the same issue. My set up is a clean install of tangermeme using pip, after installing torch 2.4.1, on Ubuntu using python 3.12.7.

**Comment by jmschrei** [comment] 2024-10-14 11:15
Can you try cloning the repo using `git clone https://github.com/jmschrei/tangermeme`, running `cd tangermeme` to get into that directory, and then running `pip install -e .` there, and then running the unit tests with `pytest -s -v tests/` and see if it works?

**Comment by Vejni** [comment] 2024-10-14 12:48
That also fails, here is the test summary 

=========================== short test summary info ============================
FAILED tests/test_annotate.py::test_annotate_seqlets - numba.core.errors.Typi...
FAILED tests/test_annotate.py::test_annotate_seqlets_n_nearest - numba.core.e...
FAILED tests/test_annotate.py::test_annotate_seqlets_reverse_complement - num...
FAILED tests/test_deep_lift_shap.py::test_captum_deep_lift_shap_summodel - Mo...
FAILED tests/test_deep_lift_shap.py::test_captum_deep_lift_shap_flattendense
FAILED tests/test_deep_lift_shap.py::test_captum_deep_lift_shap_scatter - Mod...
FAILED tests/test_deep_lift_shap.py::test_captum_deep_lift_shap_conv - Module...
FAILED tests/test_deep_lift_shap.py::test_captum_deep_lift_shap_batch_size - ...
FAILED tests/test_deep_lift_shap.py::test_captum_deep_lift_shap_n_shuffles - ...
FAILED tests/test_deep_lift_shap.py::test_captum_deep_lift_shap_args - Module...
FAILED tests/tools/test_cmd_tomtom.py::test_cmd_tomtom - pandas.errors.EmptyD...
FAILED tests/tools/test_cmd_tomtom.py::test_cmd_tomtom2 - pandas.errors.Empty...
FAILED tests/tools/test_tomtom.py::test_tomtom - numba.core.errors.TypingErro...
FAILED tests/tools/test_tomtom.py::test_tomtom_subsets - numba.core.errors.Ty...
FAILED tests/tools/test_tomtom.py::test_tomtom_meme - numba.core.errors.Typin...
FAILED tests/tools/test_tomtom.py::test_tomtom_reverse_complement - numba.cor...
FAILED tests/tools/test_tomtom.py::test_tomtom_n_jobs - numba.core.errors.Typ...
FAILED tests/tools/test_tomtom.py::test_tomtom_n_nearest - numba.core.errors....
FAILED tests/tools/test_tomtom.py::test_tomtom_n_target_bins_small - numba.co...
================ 19 failed, 296 passed, 574 warnings in 39.44s =================

**Comment by jmschrei** [comment] 2024-10-14 12:55
Just checking -- are the `deep_lift_shap` tests failing because you don't have captum?

**Comment by Vejni** [comment] 2024-10-14 12:59
Great, thanks for being so quick about this! 
And yes, they are failing only because of captum.

**Comment by jmschrei** [comment] 2024-10-14 13:29
That was faster than expected. Can you try 0.4.1 and let me know if that resolves the issue?

**Comment by Vejni** [comment] 2024-10-14 14:01
Well... Actually. This version seems to break something in plot_logo. The error thrown is:

`LogomakerError: type(floor) =  must be a number`

You can recreate it with any plot_logo call, e.g.:

`import torch
from tangermeme.utils import random_one_hot
from matplotlib import pyplot as plt
import seaborn; seaborn.set_style('whitegrid')
from tangermeme.plot import plot_logo

X = random_one_hot((1, 4, 2000), random_state=0).type(torch.float32)

plt.figure(figsize=(10, 2))
ax = plt.subplot(111)
plot_logo(X[0, :, 950:1050], ax=ax)

plt.xlabel("Genomic Position")
plt.ylabel("Value")

plt.tight_layout()
plt.show()
`

Switching to 0.4.0. it runs without an issue. It is beyond me how this can happen.

**Comment by Vejni** [comment] 2024-10-14 14:08
OK. Casting the tensor to int, or double (for attributions) the plotting works.

**Comment by shirondru** [comment] 2024-10-14 15:42
Thank you both for your help with this!

**Comment by jmschrei** [comment] 2024-10-14 18:24
I'm going to close this. Please re-open if you continue to encounter issues. @Vejni I think that has been reported elsewhere, and I will look into it.

**Closed by jmschrei** 2024-10-14 18:24 UTC
